const { chromium } = require('playwright');
const fs = require('fs');
const path = require('path');

// Embedded font data (base64) — guarantees PDF export works in any environment
// (Hugging Face / Docker / local) without relying on Git LFS-checked-out files.
// Generated by: node scripts/build-fonts-bundle.js
let EMBEDDED_FONTS = {};
try { EMBEDDED_FONTS = require('./fonts_bundle'); } catch (e) {
  console.warn('[PDF] fonts_bundle.js not found — will fall back to font files on disk');
}

const FONT_DIR = path.join(__dirname, 'assets', 'fonts');

function fontFaceCss() {
  const fonts = [
    { family: 'TheSansArabic-Light', file: 'TheSansArabic-Light.otf', format: 'opentype' },
    { family: 'TheSansArabic-Bold', file: 'BahijTheSansArabic-Bold.ttf', format: 'truetype' },
  ];
  return fonts.map(f => {
    const embedded = EMBEDDED_FONTS[f.family.replace(/-/g, '_')];
    let srcUrl = null;

    // 1) Prefer embedded base64 data (always valid, environment-independent)
    if (embedded && embedded.data && embedded.data.length > 1000) {
      const mime = f.format === 'opentype' ? 'font/otf' : 'font/ttf';
      srcUrl = 'data:' + mime + ';base64,' + embedded.data;
    } else {
      // 2) Fall back to reading the file from disk
      const fp = path.join(FONT_DIR, f.file);
      if (fs.existsSync(fp)) {
        const buf = fs.readFileSync(fp);
        // Reject Git-LFS pointer stubs (tiny files starting with "version https://git-lfs")
        const isPointer = buf.length < 500 || buf.toString('utf8', 0, Math.min(100, buf.length)).indexOf('git-lfs') !== -1;
        if (isPointer) {
          console.warn('[PDF] Font file is an LFS pointer (not real data), skipping:', fp);
        } else {
          const mime = f.format === 'opentype' ? 'font/otf' : 'font/ttf';
          srcUrl = 'data:' + mime + ';base64,' + buf.toString('base64');
        }
      } else {
        console.warn('[PDF] Font not found on disk:', fp);
      }
    }

    if (!srcUrl) return '';
    return `@font-face { font-family: '${f.family}'; src: url('${srcUrl}') format('${f.format}'); font-weight: normal; font-style: normal; }`;
  }).join('\n');
}

function baseCss() {
  return `
@page { size: 1280px 720px; margin: 0; }
* { margin: 0; padding: 0; box-sizing: border-box; }
${fontFaceCss()}
body { direction: rtl; font-family: 'TheSansArabic-Light', 'TheSansArabic-Bold', Tahoma, Arial, sans-serif; }
.slide { width: 1280px; height: 720px; direction: rtl; position: relative; overflow: hidden; page-break-after: always; page-break-inside: avoid; }
.slide:last-child { page-break-after: auto; }
img { max-width: 100%; max-height: 100%; object-fit: cover; }
`;
}

// Render a single slide's HTML into a PNG screenshot (base64 data URI).
// Used by the designer-chat so GLM can "see" the current slide visually.
// opts.scale controls resolution (default 2 for crisp text).
async function renderSlideImage(slideHtml, opts) {
  opts = opts || {};
  const scale = opts.scale || 2;
  const fullHtml = `<!DOCTYPE html>
<html lang="ar" dir="rtl">
<head>
  <meta charset="UTF-8">
  <style>${baseCss()}</style>
</head>
<body>
${slideHtml}
</body>
</html>`;

  let browser;
  try {
    browser = await chromium.launch({ args: ['--no-sandbox', '--disable-dev-shm-usage', '--disable-gpu', '--font-render-hinting=none'] });
    const page = await browser.newPage({ viewport: { width: 1280, height: 720 }, deviceScaleFactor: scale });
    await page.setContent(fullHtml, { waitUntil: 'load', timeout: 30000 });
    await page.waitForTimeout(800);
    const buf = await page.screenshot({ type: 'png', omitBackground: false });
    return 'data:image/png;base64,' + buf.toString('base64');
  } catch (err) {
    console.error('[PDF] Screenshot error:', err.message);
    throw err;
  } finally {
    if (browser) await browser.close();
  }
}

async function generatePdf(slidesHtml, outputPath) {
  const fullHtml = `<!DOCTYPE html>
<html lang="ar" dir="rtl">
<head>
  <meta charset="UTF-8">
  <style>${baseCss()}</style>
</head>
<body>
${slidesHtml}
</body>
</html>`;

  let browser;
  try {
    browser = await chromium.launch({ args: ['--no-sandbox', '--disable-dev-shm-usage', '--disable-gpu', '--font-render-hinting=none'] });
    const page = await browser.newPage();
    await page.setViewportSize({ width: 1280, height: 720 });
    await page.setContent(fullHtml, { waitUntil: 'load', timeout: 30000 });
    await page.waitForTimeout(1000);
    await page.evaluate(() => document.fonts.ready);

    const slides = await page.$$('.slide');
    if (slides.length === 0) {
      await page.pdf({
        path: outputPath,
        width: '1280px',
        height: '720px',
        printBackground: true,
        margin: { top: '0', right: '0', bottom: '0', left: '0' },
      });
      console.log('[PDF] Generated successfully (fallback):', outputPath);
      return outputPath;
    }

    const { PDFDocument } = require('pdf-lib');
    const pdfDoc = await PDFDocument.create();

    for (let i = 0; i < slides.length; i++) {
      const slideEl = slides[i];
      const box = await slideEl.boundingBox();
      const screenshot = await page.screenshot({
        clip: { x: box.x, y: box.y, width: 1280, height: 720 },
        type: 'png',
      });
      const pngImage = await pdfDoc.embedPng(screenshot);
      const pdfPage = pdfDoc.addPage([1280, 720]);
      pdfPage.drawImage(pngImage, { x: 0, y: 0, width: 1280, height: 720 });
    }

    const pdfBytes = await pdfDoc.save();
    require('fs').writeFileSync(outputPath, pdfBytes);
    console.log('[PDF] Generated successfully (image-based):', outputPath);
  } catch (err) {
    console.error('[PDF] Generation error:', err.message);
    throw err;
  } finally {
    if (browser) await browser.close();
  }
  return outputPath;
}

if (require.main === module) {
  const testHtml = `
<div class="slide" style="background:#FBFAF8;padding:0;">
  <div style="display:flex;align-items:center;justify-content:space-between;padding:10px 30px;border-bottom:1px solid rgba(122,12,12,0.1)">
    <span style="font-size:13px;font-weight:700;color:#7A0C0C">شركة منافع الاقتصادية للعقار</span>
    <span style="font-size:11px;color:#888">دراسة جدوى</span>
  </div>
  <div style="padding:30px">
    <div style="font-size:20px;font-weight:700;color:#7A0C0C">المؤشرات المالية</div>
    <div style="display:flex;gap:16px;margin-top:20px">
      <div style="flex:1;background:#FFF;border-radius:14px;padding:20px;box-shadow:0 2px 16px rgba(0,0,0,0.06)">
        <div style="font-size:11px;color:#888">إجمالي التكلفة</div>
        <div style="font-size:28px;font-weight:700;color:#7A0C0C">146 مليون ريال</div>
      </div>
      <div style="flex:1;background:#FFF;border-radius:14px;padding:20px;box-shadow:0 2px 16px rgba(0,0,0,0.06)">
        <div style="font-size:11px;color:#888">العائد الاستثماري</div>
        <div style="font-size:28px;font-weight:700;color:#7A0C0C">24.2%</div>
      </div>
    </div>
  </div>
</div>`;

  generatePdf(testHtml, path.join(__dirname, 'test_node_output.pdf'))
    .then(() => console.log('Done: test_node_output.pdf'))
    .catch(e => console.error(e));
}

module.exports = { generatePdf, renderSlideImage };
