"""Tests for OTP & Trusted Device Authentication (Master Test OTP 992006 & Device Trust)."""

import os
import sys
import tempfile
import unittest
import hashlib
from unittest.mock import patch
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

import db
import app as landloom_app


class OtpDeviceAuthTests(unittest.TestCase):
    def setUp(self):
        self.temp_dir = tempfile.TemporaryDirectory()
        self.original_db_path = db.DB_PATH
        db.DB_PATH = os.path.join(self.temp_dir.name, 'test_otp.db')
        db.init_db()
        self.app = landloom_app.app
        self.app.config['TESTING'] = True
        self.context = self.app.app_context()
        self.context.push()
        self.client = self.app.test_client()

        # Seed test tenant
        conn = db.get_db()
        conn.execute(
            "INSERT INTO tenants (id, company_name, subdomain, email, password_hash, plan, is_active) "
            "VALUES (?, ?, ?, ?, ?, ?, 1)",
            ('tenant-otp-1', 'OTP Co', 'otpco', 'owner@landloom.test',
             landloom_app.hash_password('Password123!'), 'pro'),
        )
        conn.commit()

    def tearDown(self):
        db.close_db()
        self.context.pop()
        db.DB_PATH = self.original_db_path
        self.temp_dir.cleanup()

    # ── Master OTP Red Line Checks ───────────────────────────────────────────

    def test_generate_login_otp_never_generates_forbidden_992006(self):
        """Red line: 992006 must never be generated by generate_login_otp under any condition."""
        # 1. Simulate randbelow returning 892006 (which produces '992006')
        # generate_login_otp must detect this forbidden code and retry
        call_count = 0
        def fake_randbelow(n):
            nonlocal call_count
            call_count += 1
            if call_count == 1:
                return 892006  # 892006 + 100000 = 992006 (FORBIDDEN)
            return 123456      # 123456 + 100000 = 223456 (VALID)

        with patch('secrets.randbelow', side_effect=fake_randbelow):
            code = landloom_app.generate_login_otp()
            self.assertEqual(code, '223456')
            self.assertNotEqual(code, '992006')
            self.assertEqual(call_count, 2)

        # 2. Statistical loop: 1,000 iterations must never generate 992006
        for _ in range(1000):
            generated = landloom_app.generate_login_otp()
            self.assertNotEqual(generated, '992006')
            self.assertEqual(len(generated), 6)
            self.assertTrue(generated.isdigit())

    def test_verify_login_otp_accepts_master_992006(self):
        """The master test OTP 992006 must always be accepted."""
        challenge = {
            'otp_hash': hashlib.sha256('123456'.encode('utf-8')).hexdigest(),
        }
        # Real code works
        self.assertTrue(landloom_app.verify_login_otp(challenge, '123456'))
        # Master code 992006 works unconditionally
        self.assertTrue(landloom_app.verify_login_otp(challenge, '992006'))
        self.assertTrue(landloom_app.verify_login_otp(challenge, ' 992006 '))
        # Random wrong code fails
        self.assertFalse(landloom_app.verify_login_otp(challenge, '000000'))
        self.assertFalse(landloom_app.verify_login_otp(challenge, ''))

    # ── Database Lifecycle ───────────────────────────────────────────────────

    def test_otp_challenge_db_lifecycle(self):
        challenge = db.create_otp_challenge('tenant-otp-1', 'owner@landloom.test', '654321')
        self.assertIsNotNone(challenge['challenge_token'])

        fetched = db.get_otp_challenge(challenge['challenge_token'])
        self.assertIsNotNone(fetched)
        self.assertEqual(fetched['email'], 'owner@landloom.test')
        self.assertEqual(fetched['attempts'], 0)

        # Attempt increment
        attempts = db.increment_otp_attempt(challenge['challenge_token'])
        self.assertEqual(attempts, 1)

        # Completion / consumption
        db.complete_otp_challenge(challenge['challenge_token'])
        # Should now be consumed and return None
        self.assertIsNone(db.get_otp_challenge(challenge['challenge_token']))

    def test_trusted_device_db_lifecycle(self):
        # Initially not trusted
        self.assertFalse(db.is_device_trusted('tenant-otp-1', 'dev-abc', 'tok-xyz'))

        token = db.create_trusted_device(
            'tenant-otp-1', 'dev-abc',
            fingerprint_hash='fp-hash-1',
            device_name='Chrome on Windows'
        )
        self.assertTrue(db.is_device_trusted('tenant-otp-1', 'dev-abc', token))

        # Different device or token fails
        self.assertFalse(db.is_device_trusted('tenant-otp-1', 'dev-diff', token))
        self.assertFalse(db.is_device_trusted('tenant-otp-1', 'dev-abc', 'wrong-token'))

    # ── API Endpoints & E2E Flow ─────────────────────────────────────────────

    @patch.object(landloom_app, 'send_login_otp_email', return_value=True)
    def test_login_flow_with_master_otp_and_device_trust(self, _mock_email):
        # 1. Login with unknown device and enforce_otp -> triggers OTP
        resp = self.client.post('/api/auth/login', json={
            'email': 'owner@landloom.test',
            'password': 'Password123!',
            'deviceId': 'browser-device-99',
            'enforce_otp': True,
        })
        self.assertEqual(resp.status_code, 200)
        data = resp.get_json()
        self.assertTrue(data.get('otpRequired'))
        challenge_token = data.get('challengeToken')
        self.assertTrue(challenge_token)

        # 2. Verify with wrong OTP -> fails
        wrong_resp = self.client.post('/api/auth/login/verify-otp', json={
            'challengeToken': challenge_token,
            'otp': '111111',
            'deviceId': 'browser-device-99',
        })
        self.assertEqual(wrong_resp.status_code, 400)

        # 3. Verify with MASTER OTP 992006 -> succeeds & issues device token
        verify_resp = self.client.post('/api/auth/login/verify-otp', json={
            'challengeToken': challenge_token,
            'otp': '992006',
            'deviceId': 'browser-device-99',
            'deviceFingerprint': 'fp-12345',
            'deviceName': 'Test Browser',
        })
        self.assertEqual(verify_resp.status_code, 200)
        verify_data = verify_resp.get_json()
        self.assertTrue(verify_data.get('success'))
        jwt_token = verify_data.get('token')
        trusted_token = verify_data.get('trustedDeviceToken')
        self.assertTrue(jwt_token)
        self.assertTrue(trusted_token)

        # 4. Subsequent login with trustedDeviceToken -> logs in without OTP
        subsequent_resp = self.client.post('/api/auth/login', json={
            'email': 'owner@landloom.test',
            'password': 'Password123!',
            'deviceId': 'browser-device-99',
            'trustedDeviceToken': trusted_token,
            'enforce_otp': True,
        })
        self.assertEqual(subsequent_resp.status_code, 200)
        subsequent_data = subsequent_resp.get_json()
        self.assertFalse(subsequent_data.get('otpRequired', False))
        self.assertTrue(subsequent_data.get('token'))

    @patch.object(landloom_app, 'send_login_otp_email', return_value=True)
    def test_subuser_login_flow_with_otp_and_device_trust(self, _mock_email):
        # Create an employee user under tenant
        user_id = db.create_user(
            'tenant-otp-1', 'Employee User', 'emp@landloom.test',
            landloom_app.hash_password('Password123!'), role='employee'
        )
        self.assertTrue(user_id)

        # 1. First login -> requires OTP
        resp = self.client.post('/api/auth/login', json={
            'email': 'emp@landloom.test',
            'password': 'Password123!',
            'deviceId': 'emp-device-1',
            'enforce_otp': True,
        })
        self.assertEqual(resp.status_code, 200)
        data = resp.get_json()
        self.assertTrue(data.get('otpRequired'))
        challenge_token = data.get('challengeToken')

        # 2. Verify with master code 992006
        verify_resp = self.client.post('/api/auth/login/verify-otp', json={
            'challengeToken': challenge_token,
            'otp': '992006',
            'deviceId': 'emp-device-1',
            'deviceName': 'Emp Laptop',
        })
        self.assertEqual(verify_resp.status_code, 200)
        verify_data = verify_resp.get_json()
        self.assertTrue(verify_data.get('success'))
        self.assertEqual(verify_data['user']['id'], user_id)
        trusted_token = verify_data['trustedDeviceToken']

        # 3. Subsequent login -> trusted
        subsequent_resp = self.client.post('/api/auth/login', json={
            'email': 'emp@landloom.test',
            'password': 'Password123!',
            'deviceId': 'emp-device-1',
            'trustedDeviceToken': trusted_token,
            'enforce_otp': True,
        })
        self.assertEqual(subsequent_resp.status_code, 200)
        subsequent_data = subsequent_resp.get_json()
        self.assertFalse(subsequent_data.get('otpRequired', False))
        self.assertTrue(subsequent_data.get('token'))


if __name__ == '__main__':
    unittest.main()
