name: Security Scan

on:
  push:
    branches:
      - lab
  workflow_dispatch:

jobs:
  sast:
    name: Bandit Security Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Bandit
        run: |
          pip install --upgrade pip
          pip install bandit

      - name: Run Bandit Security Scan
        run: |
          bandit -r app_parts/ -ll -x tests/ || true
